---
- name: My first playbook :)
  hosts: "webservers"
  become: true
  become_user: root
  vars:
     server_name: localhostNode
     cache_size: 10GB
  tasks:

    - name: debug
      debug: var=ansible_distribution

    - name: debug 
      debug: var=server_name
   
    - name: debug
      debug: var=cache_size

  roles:
    - role: copias
    - { role: geerlingguy.apache }
    - { role: geerlingguy.mysql }
